controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_logout:
    path: /logout
    methods: GET

api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint